<?php
/**
 * @return mixed
 */
function orejime_videos_config() {
  return Drupal::service('config.factory')
    ->getEditable('orejime_videos.settings');
}

/**
 * @return mixed
 */
function orejime_videos_filtered_domains() {
  return orejime_videos_config()->get('filtered_domains');
}

/**
 * Implements hook_preprocess_HOOK().
 */
function orejime_videos_preprocess_orejime_video(&$variables) {
  $variables["#attached"]["library"][] = 'orejime_videos/orejimeVideos';
  $variables["#attached"]['drupalSettings']['orejime_videos'] = [
    'consent' => orejime_videos_config()->get('orejime_consent'),
  ];
}

/**
 * Implements hook_theme().
 */
function orejime_videos_theme($existing, $type, $theme, $path) {
  return [
    'orejime_video' => [
      'variables' => [
        'original' => NULL,
        'contentID' => NULL,
      ],
    ],
  ];
}
