<?php

/**
 * Function to get domain from url
 *
 * @param $url
 * @param $consents
 *
 * @return string|null
 */
function orejime_videos_get_orejime_consent_from_url($url, $consents): ?string {
  foreach ($consents as $host => $consent) {
    if (stripos($url, $host)) {
      return $consent;
    }
  }

  return NULL;
}

/**
 * Implements hook_preprocess_HOOK().
 */
function orejime_videos_preprocess_orejime_video(&$variables) {
  $variables["#attached"]["library"][] = 'orejime_videos/orejimeVideos';
}

/**
 * Implements hook_theme().
 *
 * @param $existing
 * @param $type
 * @param $theme
 * @param $path
 *
 * @return \null[][][]
 */
function orejime_videos_theme($existing, $type, $theme, $path): array {
  return [
    'orejime_video' => [
      'variables' => [
        'original' => NULL,
        'contentID' => NULL,
        'attributes' => NULL,
        'orejime_consent' => NULL,
      ],
    ],
  ];
}
