<?php

/**
 * @return mixed
 */
function orejime_complient_videos_filtered_domains() {
  $config = Drupal::service('config.factory')->getEditable('orejime_complient_videos.settings');

  $filtered_domains = $config->get('filtered_domains');

  return $filtered_domains;
}

/**
 * Implements hook_preprocess_HOOK().
 */
function orejime_complient_videos_preprocess_orejime_video(&$variables) {
  $variables["#attached"]["library"][] = 'orejime_complient_videos/orejimeVideos';
}

/**
 * Implements hook_theme().
 */
function orejime_complient_videos_theme($existing, $type, $theme, $path) {
  return [
    'orejime_video' => [
      'variables' => [
        'original' => NULL,
        'contentID' => NULL,
      ],
    ],
  ];
}
