<?php

/**
 * Implements hook_preprocess_HOOK().
 */
function orejime_complient_videos_preprocess_orejime_video(&$variables) {
  $variables["#attached"]["library"][] = 'orejime_complient_videos/orejimeVideos';
}

/**
 * Implements hook_theme().
 */
function orejime_complient_videos_theme($existing, $type, $theme, $path) {
  return [
    'orejime_video' => [
      'variables' => [
        'original' => NULL,
        'height' => NULL,
        'width' => NULL,
        'videoID' => NULL,
      ],
    ],
  ];
}
